# Generated by Django 2.2.7 on 2019-11-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20191129_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='running',
            field=models.BooleanField(null=True),
        ),
    ]
