# Generated by Django 2.2.7 on 2019-11-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20191129_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='approaches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='chasing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='climbing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='eating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='foraging',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='indifferent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='kuks',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='moans',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='quaas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='runs_from',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='tail_flags',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='tail_twitches',
            field=models.BooleanField(null=True),
        ),
    ]
